import { Inter } from 'next/font/google'
import './globals.css'
import SessionProvider from './components/SessionProvider'
import { getServerSession } from 'next-auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
//make RootLayout an async function and await getServerSession()
export default async function RootLayout({ children }) {

  const session = await getServerSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        {/*wrap children in SessionProvider and pass session as prop*/}
        <SessionProvider session={session}>
          <main>
            {children}
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}